variable "fleet_name" {
  description = "Name of the FleetMind fleet. Used to namespace all AWS resources and workspace paths."
  type        = string
  default     = "fleetmind"
}

variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = "EC2 instance type. t3.medium comfortably runs 3 OpenClaw agents. Scale up if adding more."
  type        = string
  default     = "t3.medium"
}

variable "agent_names" {
  description = "List of agent names. Each gets its own systemd service and workspace subdirectory."
  type        = list(string)
  default     = ["orchestrator", "pixel", "forge"]
}

variable "agent_ports" {
  description = "Map of agent name to OpenClaw port."
  type        = map(number)
  default = {
    orchestrator = 18789
    pixel        = 18790
    forge        = 18791
  }
}

variable "openclaw_version" {
  description = "OpenClaw npm package version to install. Use 'latest' or pin to a specific version."
  type        = string
  default     = "latest"
}

variable "node_version" {
  description = "Node.js major version to install via nvm."
  type        = string
  default     = "22"
}

variable "rds_instance_class" {
  description = "RDS instance class for the shared Postgres database."
  type        = string
  default     = "db.t3.micro"
}

variable "rds_multi_az" {
  description = "Enable Multi-AZ for RDS. Set true for production."
  type        = bool
  default     = false
}

variable "rds_allocated_storage" {
  description = "Allocated storage in GB for RDS."
  type        = number
  default     = 20
}

variable "allowed_ssh_cidrs" {
  description = "CIDRs allowed to SSH to the fleet instance. Default empty — use SSM Session Manager instead."
  type        = list(string)
  default     = []
}

variable "ami_id" {
  description = "AMI ID override. Defaults to latest Amazon Linux 2023 if left empty."
  type        = string
  default     = ""
}

variable "vpc_id" {
  description = "ID of an existing VPC to deploy into. Leave empty to create a new VPC."
  type        = string
  default     = ""
}

variable "existing_public_subnet_ids" {
  description = "IDs of existing public subnets (2 required) when deploying into an existing VPC."
  type        = list(string)
  default     = []
}

variable "existing_private_subnet_ids" {
  description = "IDs of existing private subnets (2 required) when deploying into an existing VPC."
  type        = list(string)
  default     = []
}

variable "enable_rds" {
  description = "Deploy RDS Postgres. Set false to use DynamoDB ContextStore only (simpler, lower cost)."
  type        = bool
  default     = false
}

# ── Per-agent overrides (optional) ────────────────────────────────────────────
# All default to empty maps so existing deployments are unaffected.
# Use these in tfvars to give specific agents different sizing.

variable "agent_instance_types" {
  description = "Per-agent EC2 instance type overrides (map of agent_id → instance_type). Falls back to var.instance_type for any agent not listed."
  type        = map(string)
  default     = {}
}

variable "agent_models" {
  description = "Per-agent model override (map of agent_id → model string). Informational — records which LLM model each agent uses. Not consumed at EC2 provisioning time; model is set in the OpenClaw workspace config (openclaw.json) generated by 'fleetmind deploy'."
  type        = map(string)
  default     = {}
}

variable "agent_orchestrators" {
  description = "Map of agent_id → bool indicating which agents are PM/orchestrator bots. Used by the task-ledger module to split IAM policy attachments: orchestrators get the pm policy; non-orchestrators get the worker policy."
  type        = map(bool)
  default     = {}
}

variable "delegation_enabled" {
  description = "When true, instantiates the task-ledger module which provisions the DynamoDB task table, S3 narratives bucket, EventBridge Pipe, and DLQ infrastructure needed for the bot-delegation flow. Set false if delegation infra was applied separately or is not needed."
  type        = bool
  default     = true
}

variable "enable_interface_endpoints" {
  description = "Provision VPC interface endpoints for SSM (ssm, ssmmessages, ec2messages) and Secrets Manager. Adds ~$80/mo (4 endpoints × ~$20/mo). Default false. Recommended for fleets in fully-private subnets without NAT, or operators who want SSM resilience independent of NAT health."
  type        = bool
  default     = false
}

variable "wake_target_session_key" {
  description = "OpenClaw session key used by the task-ledger EventBridge rule to wake the PM bot via SSM Run Command when a terminal task event fires. Format: agent:main:slack:channel:<channel_id>. Required (non-empty) when delegation_enabled = true."
  type        = string
  default     = ""
}

variable "fleetmind_version" {
  description = "Version of @continuous-agentics/fleetmind to install on each agent EC2."
  type        = string
  default     = "latest"
}

variable "secret_recovery_window_days" {
  description = "AWS Secrets Manager recovery window (days) after deletion. Used for per-agent slack/anthropic secrets and the optional RDS master password secret. Set to 0 to disable recovery (delete immediately) — useful for ephemeral test fleets."
  type        = number
  default     = 7
}
